version: '2'

services:
  ftps:
    image: stilliard/pure-ftpd
    ports:
      - "2220:21"
      - "30000-30009:30000-30009"
    volumes:
#     Local端存放資料位置
      - "./data:/home/Fen/"
#     Local端存放FTP設定位置
      - "./passwd:/etc/pure-ftpd/passwd"
#     Local端存放SSL Key位置
      - "./ssl_key:/etc/ssl/private/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: Fen
      FTP_USER_PASS: 870504
      FTP_USER_HOME: /home/Fen
      ADDED_FLAGS: "--tls=2"
  ftp:
    image: stilliard/pure-ftpd
    ports:
      - "2221:21"
      - "30010-30019:30010-30019"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: Fen
      FTP_USER_PASS: 870504
      FTP_USER_HOME: /home/Fen
      FTP_PASSIVE_PORTS: "30010:30019"
  sftp:
    image: atmoz/sftp
    ports:
        - "2222:22"
    command: Fen:870504:::upload
  sftpssh:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "2223:22"
#   參數為 User:Password:UID:GID:created RemoteDir
#   未輸入密碼為只使用private key  登入 
    command: Fen::::upload
  

