version: '2'

services:
  ftp:
    image: stilliard/pure-ftpd
    ports:
      - "2220:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "127.0.1.0"
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: 000000
      FTP_USER_HOME: /home/Fen
  ftps:
    image: stilliard/pure-ftpd
    ports:
      - "2221:21"
      - "30010-30019:30010-30019"
    volumes:
#     Local端存放資料位置
      - "./data:/home/Fen/"
#     Local端存放FTP設定位置
      - "./passwd:/etc/pure-ftpd/passwd"
#     Local端存放SSL Key位置
      - "./ssl_key:/etc/ssl/private/"
    environment:
      PUBLICHOST: "127.0.2.0"
      FTP_USER_NAME: ftpsuser
      FTP_USER_PASS: 000000
      FTP_USER_HOME: /home/Fen
      ADDED_FLAGS: "--tls=2"

  sftp:
    image: atmoz/sftp
    ports:
        - "2222:22"
    command: sftpuser:000000:::upload
  sftpssh:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "2223:22"
#   參數為 User:Password:UID:GID:created RemoteDir
#   未輸入密碼為只使用private key  登入 
    command: sshuser::::upload
  

